# Project: hep 1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = hep_1_private.res
OBJ      = "hep\ 1.0.o" $(RES)
LINKOBJ  = "hep 1.0.o" $(RES)
LIBS     = -L"F:/C++/DevCpp/Dev-Cpp/MinGW64/lib" -L"F:/C++/DevCpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/include" -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/include" -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/C++/DevCpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = hep.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++14
CFLAGS   = $(INCS) -g3 -std=c++14
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"hep\ 1.0.o": hep\ 1.0.cpp
	$(CPP) -c "hep 1.0.cpp" -o "hep 1.0.o" $(CXXFLAGS)

hep_1_private.res: hep_1_private.rc 
	$(WINDRES) -i hep_1_private.rc --input-format=rc -o hep_1_private.res -O coff 

